### PR TITLE
Bobaguardian/issue381

### LINKED ISSUE #381: Combine "Gold on Fire" and "Free Gold?" events

### PR DESCRIPTION
**Pull request by bobaguardian**
- combine free gold and gold on fire
- damage is 50% chance
- removed other 2 rooms from the room dictionary, but files are still there in case we want them back

### CODE REVIEW

**Review by ntseng — CHANGES_REQUESTED** [review]
Please use `helpers.js`'s `generateRandomNumber()` instead of `Math.random()`. That way the outcome of the event will be tied to the adventure's seed.

Otherwise, looks good! Great planning ahead with creating `goldCount` and `damageChance`.

**Comment by bobaguardian** [comment]
Oh interesting, how is it tied to the adventure's seed?  Should I make it affect the damage chance?

**Comment by ntseng** [comment]
The game uses a hashing function to roll a random number table at the beginning of each adventure, and then `generateRandomNumber()` reads from that table. That way giving the same starting seed can always lead to the same (difficult to predict) outcomes.

Design-wise if we want to randomize either gold value or damage chance, I'd investigate gold value first. Varying probability tends not to be very intuitive gameplay (and thus not very popular) in my experience.

Previous playtesting noted that 50 gold for 100 damage felt a little low, so adding a chance to avoid the damage might make it lucrative enough to take. On the other hand, given that 50 gold is only 1/4th of a weapon from a merchant, this event might not be rewarding enough in general. It's plausible that this is balanced, so we should probably just playtest before tweaking much more stuff.

**Review by ntseng — APPROVED** [review]
Great work. Let's save tuning the gold value for after the next round of playtesting.

**Pull request merged**
