### PR TITLE
v0.9.0 Dev Tool

### PR DESCRIPTION
**Pull request by ntseng**
- improved deploy script to not require inject config pattern

### CODE REVIEW

**Review by doubledh — APPROVED** [review]
Woo! Test the updateCommands.js without a config file (rename it or something), before merging, though

**Review by doubledh — CHANGES_REQUESTED** [review]
Pulled branch down, I'm getting errors using the config blueprint file, on upload_commands.js

**Comment by ntseng** [comment]
> Woo! Test the updateCommands.js without a config file (rename it or something), before merging, though

Running `updateCommands.js` without any config files still fails (as expected). The change to the `deploy.yaml` is targeted at preventing that from happening though.

**Review by doubledh — APPROVED** [review]
nvm, forgot it was "updateCommands" to be tested, not "uploadCommands". blueprint-config files work with updateCommands locally, for me. Nice work

**Pull request merged**
